name: CI
on: [push, pull_request]
jobs:
  precommit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.6.8"

      - name: run custom python
        run: uv run cli-check exit-code-zero

      - name: Install dependencies using uv
        run: uv run pip install pre-commit

      - name: Run pre-commit hooks
        run: pre-commit run --all-files
